apiVersion: apps/v1
kind: Deployment
metadata:
  name: extra-credit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sivani16448387
  template:
    metadata:
      labels:
        app: sivani16448387
    spec:
      containers:
      - name: sivani16448387
        image: sivani16448387:latest # Replace with your Docker image name
        ports:
        - containerPort: 8080